name: bmi_project
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  page_transition: ^1.1.4
  fancy_bottom_navigation: ^0.3.2
  curved_navigation_bar: ^0.3.0
  font_awesome_flutter: ^8.5.0



dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true

  assets:
  - images/

  fonts:
  - family: OpenSans-Regular
    fonts:
    - asset: fonts/OpenSans-Regular.ttf
    - asset: fonts/OpenSans-SemiBold.ttf
    - asset: fonts/OpenSans-Light.ttf



